# Generated by Django 5.0.2 on 2024-03-30 00:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodieApp', '0002_coctel_tips_delete_categoria_delete_etiqueta_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tips',
            new_name='Tip',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='tip',
        ),
        migrations.AlterField(
            model_name='coctel',
            name='imagen',
            field=models.ImageField(upload_to='media/imagenes_recetas/'),
        ),
    ]
